### ISSUE TITLE
Website: Write guideline for "About" Sections

### ISSUE THREAD

**Issue by quickst3r** [quickstain/quickstain-website#6]
We should create a guideline for "About"-Sections on the QS-Website.

Will be used for "About the Team" Section at the QS-Website.

**Comment by quickst3r** [comment]
Aboutformular, quickstainteam:

In der "Developeraufnahme" Datei werden schon die Relevanten Dinge für die Admins abgefragt nur ein 
paar Dinge sollten öffentlich einsehbar sein
*forumname:
*githubname:
age:
*Country:
realname:
hobbys: 
more:

pic:
motivation/reason:

**Comment by staincatcher** [comment]
Again, great draft.

Same here with Age and Year of birth, shouldn't it be the same?

Further more: GitHub and Forum Usernames shouldn't be optional!

**Comment by quickst3r** [comment]
1 no its not the same, year is because age isnt actuell after one year and age is for easier to see, how old somebody is
2 For Team is importand who this guy is in github, if no githubname we Need an area for the githubnames in github. And Forumname is importand to see who is working on

**Comment by staincatcher** [comment]
I don't get it!

Asterisks (Sternchen) means: this Point is mandatory (verpflichtend)?

**Comment by quickst3r** [comment]
yes it means that but we working on, we speak about what would be better, wich way

**Comment by staincatcher** [comment]
Could you post an alternative?

**Comment by quickst3r** [comment]
The alternative:
 Please answer the following questions.

**Comment by staincatcher** [comment]
Accepted.
